server:
  port: 38089
  servlet:
    context-path: /

spring:
  application:
    name: thread-dump-analyzer
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    com.archithreads.analyzer: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/thread-dump-analyzer.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
